# Generated by Django 3.2.16 on 2022-10-07 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default="Admin User",
                help_text="User's full name.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]*$", "Only alphabetic characters are allowed."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False, help_text="Owner User."),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
